anfr: {
  id_systeme: {
    shape: sql_table
    sys_id: int {constraint: primary_key}
    sys_lb: text
  }
  id_bande: {
    shape: sql_table
    ban_id: int {constraint: primary_key}
    fmin: int
    fmax: int
  }
  id_type_antenne: {
    shape: sql_table
    tae_id: int {constraint: primary_key}
    tae_lb: text
  }
  id_nature: {
    shape: sql_table
    nat_id: int {constraint: primary_key}
    nat_lb: text
  }
  id_proprietaire: {
    shape: sql_table
    tpo_id: int {constraint: primary_key}
    tpo_lb: text
  }
  id_exploitant: {
    shape: sql_table
    adm_id: int {constraint: primary_key}
    adm_lb: text
  }

  site: {
    shape: sql_table
    site_id: int {constraint: primary_key}
    dms: text
    lat: float
    lon: float
    address: text
    postcode: text
    inseecode: int
  }

  emetteur: {
    shape: sql_table
    emr_id: int {constraint: primary_key}
    sta_id: text {constraint: foreign_key}
    aer_id: int {constraint: foreign_key}
    sys_id: int {constraint: foreign_key}
    emr_dt_service: timestamp
  }
  emetteur.sys_id -> id_systeme.sys_id
  emetteur.aer_id -> antenne.aer_id
  emetteur.sta_id -> station.sta_id

  banemr: {
    shape: sql_table
    emr_id: int {constraint: foreign_key}
    ban_id: int {constraint: foreign_key}
  }
  banemr.emr_id -> emetteur.emr_id
  banemr.ban_id -> id_bande.ban_id

  antenne: {
    shape: sql_table
    aer_id: int {constraint: primary_key}
    tae_id: int {constraint: foreign_key}
    sup_id: int {constraint: foreign_key}
    dimension: float
    azimut: int
    alt_bas: float
  }
  antenne.tae_id -> id_type_antenne.tae_id
  antenne.sup -> support.sup_id

  support: {
    shape: sql_table
    sup_id: int {constraint: primary_key}
    nat_id: int {constraint: foreign_key}
    tpo_id: int {constraint: foreign_key}
    site_id: int {constraint: foreign_key}
    haut: int
  }
  support.nat_id -> id_nature.nat_id
  support.tpo_id -> id_proprietaire.tpo_id
  support.site_id -> site.site_id

  station: {
    shape: sql_table
    sta_id: text {constraint: primary_key}
    adm_id: int {constraint: foreign_key}
    comsis_id: int
    dte_implantation: timestamp
    dte_modif: timestamp
    dte_en_service: timestamp
  }
  station.adm_id -> id_exploitant.adm_id

  staant: {
    shape: sql_table
    sta_id: text {constraint: foreign_key}
    aer_id: int {constraint: foreign_key}
  }
  staant.sta_id -> station.sta_id
  staant.aer_id -> antenne.aer_id
}
