anfr: {
  id_systems: {
    shape: sql_table
    id: int {constraint: primary_key}
    system: text
  }
  id_bands: {
    shape: sql_table
    id: int {constraint: primary_key}
    fmin: int
    fmax: int
  }
  id_antenna_types: {
    shape: sql_table
    id: int {constraint: primary_key}
    antenna_type: text
  }
  id_support_types: {
    shape: sql_table
    id: int {constraint: primary_key}
    support_type: text
  }
  id_support_owners: {
    shape: sql_table
    id: int {constraint: primary_key}
    support_owner: text
  }
  id_operators: {
    shape: sql_table
    id: int {constraint: primary_key}
    operator: text
  }

  sites: {
    shape: sql_table
    id: int {constraint: primary_key}
    dms: text
    lat: float
    lon: float
    address: text
    postcode: text
    inseecode: int
  }

  transmitters: {
    shape: sql_table
    id: int {constraint: primary_key}
    station_id: text {constraint: foreign_key}
    antenna_id: int {constraint: foreign_key}
    system_id: int {constraint: foreign_key}
    date_switchedon: timestamp
  }
  transmitters.system_id -> id_systems.id
  transmitters.antenna_id -> antennas.id
  transmitters.station_id -> stations.id

  transmitters_bands: {
    shape: sql_table
    transmitter_id: int {constraint: foreign_key}
    band_id: int {constraint: foreign_key}
  }
  transmitters_bands.transmitter_id -> transmitters.id
  transmitters_bands.band_id -> id_bands.id

  antennas: {
    shape: sql_table
    id: int {constraint: primary_key}
    anttype_id: int {constraint: foreign_key}
    sup_id: int {constraint: foreign_key}
    dimension: float
    azimuth: int
    ant_height: float
  }
  antennas.anttype_id -> id_antenna_types.id
  antennas.sup_id -> supports.id

  supports: {
    shape: sql_table
    id: int {constraint: primary_key}
    suptype_id: int {constraint: foreign_key}
    owner_id: int {constraint: foreign_key}
    site_id: int {constraint: foreign_key}
    sup_height: int
  }
  supports.suptype_id -> id_support_types.id
  supports.owner_id -> id_support_owners.id
  supports.site_id -> sites.id

  stations: {
    shape: sql_table
    id: int {constraint: primary_key}
    operator_id: int {constraint: foreign_key}
    station_name: text
    date_created: timestamp
    date_modified: timestamp
    date_operational: timestamp
  }
  stations.operator_id -> id_operators.id
}
